= Querying with {sqlpp}
:page-toclevels: 2
:example-source: devguide:example$node/src/sqlpp.js
:description: You can query for documents in Couchbase using the {sqlpp} query language, a language based on SQL, but designed for structured and flexible JSON documents.


[abstract]
{description}



On this page we dive straight into using the Query Service API from the {name-sdk}.
For a deeper look at the concepts, to help you better understand the Query Service, and the {sqlpp} language, see the links in the <<further-information,Further Information>> section at the end of this page.




Here we show queries against the Travel Sample collection, at cluster and scope level,
and give links to information on adding other collections to your data.
// kafka
// postgres
// capella


== Before You Start

This page assumes that you have xref:hello-world:start-using-sdk.adoc[installed the {name-sdk}], and created an xref:enterprise-analytics:install:introduction-linux-installation.adoc[Enterprise Analytics cluster].

Create a collection to work upon by xref:enterprise-analytics:intro:connecting-to-data-sources.adoc#import-the-travel-sample-collections[importing the travel-sample dataset] into your cluster.



== Querying Your Dataset

Most queries return more than one result, and you want to iterate over the results:

.Scope Level
[source,javascript]
----
include::{example-source}[indent=0,tag=sqlpp_scope_query]
----

.Cluster Level
[source,javascript]
----
include::{example-source}[indent=0,tag=sqlpp_cluster_query]
----


=== Positional and Named Parameters

Supplying parameters as individual arguments to the query allows the query engine to optimize the parsing and planning of the query. You can either supply these parameters by name or by position.

Execute an async query with positional arguments:

.Positional Parameters
[source,javascript]
----
include::{example-source}[indent=0,tag=sqlpp_positional_parameters_query]
----

Execute an async query with named arguments:

.Named Parameters
[source,javascript]
----
include::{example-source}[indent=0,tag=sqlpp_named_parameters_query]
----




== Query Options

The Query Service provides an array of options to customize your query.
The following table lists them all:

.Available Query Options
[options="header"]
|====
| Name       | Description
| `abortSignal?: AbortSignal` | Sets an abort signal for the query allowing the operation to be cancelled.
| `clientContextId?: string` | The returned client context id for this query.
| `deserializer?: Deserializer` | Sets the deserializer used by `QueryResult.rows` to convert query result rows into objects. If not specified, defaults to the cluster's default deserializer.
a| 
[source,javascript]
----
namedParameters?: {
    [key: string]: any;
}
----
| Named values to be used for the placeholders within the query.
| `positionalParameters?: any[]` | Positional values to be used for the placeholders within the query.
a| 
[source,javascript]
----
raw?: {
    [key: string]: any;
}
----
| Specifies any additional parameters which should be passed to the query engine when executing the query.
| `readOnly?: boolean` | Indicates whether this query should be executed in read-only mode.
| `scanConsistency?: QueryScanConsistency` | Specifies the consistency requirements when executing the query.
| `timeout?: number` | The timeout for this operation, represented in milliseconds.
|====




== Further Information


The xref:server:analytics:1_intro.adoc[{sqlpp} for Analytics Reference]
offers a complete guide to the SQL++ language for both of our analytics services, including all of the latest additions.


