= Compatibility
:description: Platform compatibility, and features available in different SDK versions, and compatibility between Server and SDK. \
Plus notes on Cloud, networks, and AWS Lambda.
:page-toclevels: 3
:table-caption!:


[abstract]
{description}





== Platform Compatibility


=== Node.js Version Compatibility

The {sdk_dot_minor} Node.js SDK will run on recent LTS versions of Node.js: 24 and 22.
We recommend using the most recent long-term support (LTS) version of Node.js -- 
at the time of writing (August 2025) this is version 24.
 
TIP: Remember to keep your Node.js installation up to date, via `npm`.



=== OS Compatibility

include::{sdk_api}@analytics-sdk:shared:partial$compatibility.adoc[tag=os-compat]





=== Network Requirements

include::{sdk_api}@analytics-sdk:shared:partial$network-requirements.adoc[tag=lan-like]






== Enterprise Analytics Compatibility


The 1.1 releases of the Analytics SDK is fully compatible with all currently supported releases of Enterprise Analytics.
The 1.1 {name_platform} SDK also supports an asynchronous (streaming) API update in the latest (2.2) release of self-managed Enterprise Analytics Server.


////
is a fully hosted service, continually updated, and offering the latest version --
with users having a few weeks to upgrade from the previous version.
As such, the latest Couchbase Columnar SDKs are tested against the latest versions.
Where older versions of the {name-sdk} pre-date significant new features in Columnar, those differences will be noted in this section.
////






=== API Version

include::{sdk_api}@columnar-sdk:shared:partial$compatibility.adoc[tag=api-version]




== SDK API Stability


=== Interface Stability

include::{version-common}@analytics-sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]





////
=== Older Analytics SDK Versions

include::{version-common}@columnar-sdk:shared:partial$archive.adoc[tag=link]
////

////
Note the https://www.couchbase.com/support-policy[End of Life dates^] for {name-sdk} versions.
See the notes there for Support details.
////


// Something on Columnar SDKs??
