= {name-sdk} Quickstart Guide
:page-toclevels: 3
:description: Install, connect, try. A quick start guide to get you up and running with Enterprise Analytics and the {name-sdk}.

[abstract]
{description}


include::analytics-sdk:shared:partial$start-using-sdk.adoc[tag=intro]


== Before You Start

Install and configure an xref:enterprise-analytics:intro:intro.adoc[Enterprise Analytics Cluster].

////
Sign up for a xref:cloud:get-started:create-account.adoc[Capella account],
and choose a xref:columnar:intro:intro.adoc[Columnar] cluster.

You'll need to add your IP address to the allowlist, during the sign-up and cluster creation process (this can also be done at any time, via the UI, should the address change, or if you need to add a new one).
////


=== Prerequisites

The Analytics Node.js SDK supports LTS versions of Node.js --
these are 24 and 22 at the time of the 1.0.0 release (August 2025).
See the xref:project-docs:compatibility.adoc#platform-compatibility[compatibility page] for more information about platform support.

////
We recommend using the most recent long-term support (LTS) version of Node.js -- 
at the time of writing (August 2025) this is version 24.
////

== Getting the SDK

The SDK can be installed via `npm`:

[source,console]
----
npm install couchbase-analytics
----

For other installation methods, see the xref:project-docs:sdk-full-installation.adoc[installation page].


[quickstart]
== Connecting and Executing a Query


{name-sdk} 1.1 adds support for JWT and client certificate authentication, as well as a new {async-server-api-feature-name} that uses request handles to fetch results.
Introduced in the self-managed Enterprise Analytics Server 2.2, this API eliminates the need for long-running server connections.

The examples in this first section of the page are for the standard API -- async on the client side -- working with Enterprise Analytics 2.0 and later (with {async-server-api-feature-name} examples following in the <<#server-asynchronous-api,Server Async section>>).
You can still use this API with Enterprise Analytics 2.2 and later, in addition to the new API.

=== Server Synchronous Request API

==== CommonJS

[source,javascript]
----
include::devguide:example$node/src/startusing_commonjs.js[indent=0,tag=commonjs]
----

==== ES Modules

[source,javascript]
----
include::devguide:example$node/src/startusing_esmodules.js[indent=0,tag=esmodules]
----



[[server-asynchronous-api]]
=== {async-server-api-feature-name}

Enterprise Analytics 2.2 introduces a {async-server-api-feature-name}.
The SDK sends a request, polls for results, and then fetches once the result is available.

==== CommonJS

.Server Asynchronous API Example
[source,javascript]
----
include::devguide:example$node/src/server_async.js[indent=0,tag=server-async]
----

==== ES Modules

[source,typescript]
----
include::devguide:example$node/src/server_async.ts[indent=0,tag=server-async]
----



=== Connection String

The `clusterConnStr` in the above example should takes the form of "https://<your_hostname>:" + PORT.
include::{version-common}@analytics-sdk:shared:partial$connstr.adoc[tag=connstr]




== Migration from Row-Based Analytics

include::{version-common}@analytics-sdk:shared:partial$migration.adoc[tag=migration]
